[
    {
        "content": "<p>SupernaviX opened <a href=\"https://github.com/bytecodealliance/wasmtime/issues/10088\">issue #10088</a>:</p>\n<blockquote>\n<p>Hello!</p>\n<p>I'm contributing to a project which calls async wasmtime exports. Sometimes, those exported functions start failing with the error \"wasm trap: cannot enter component instance\". I think the issue might be that the generated wasm client isn't cancel-safe.</p>\n<p>Here's the relevant snippet from the generated code (generated by wit-bindgen 0.38):</p>\n<div class=\"codehilite\" data-code-language=\"Rust\"><pre><span></span><code><span class=\"w\">            </span><span class=\"kd\">let</span><span class=\"w\"> </span><span class=\"n\">_enter</span><span class=\"w\"> </span><span class=\"o\">=</span><span class=\"w\"> </span><span class=\"n\">span</span><span class=\"p\">.</span><span class=\"n\">enter</span><span class=\"p\">();</span>\n<span class=\"w\">            </span><span class=\"kd\">let</span><span class=\"w\"> </span><span class=\"n\">callee</span><span class=\"w\"> </span><span class=\"o\">=</span><span class=\"w\"> </span><span class=\"k\">unsafe</span><span class=\"w\"> </span><span class=\"p\">{</span>\n<span class=\"w\">                </span><span class=\"n\">wasmtime</span><span class=\"p\">::</span><span class=\"n\">component</span><span class=\"p\">::</span><span class=\"n\">TypedFunc</span><span class=\"p\">::</span><span class=\"o\">&lt;</span><span class=\"p\">(</span><span class=\"kt\">u32</span><span class=\"p\">,</span><span class=\"w\"> </span><span class=\"o\">&amp;</span><span class=\"n\">Event</span><span class=\"p\">,),(</span><span class=\"nb\">Result</span><span class=\"o\">&lt;</span><span class=\"n\">Response</span><span class=\"p\">,</span><span class=\"n\">HandleError</span><span class=\"o\">&gt;</span><span class=\"p\">,)</span><span class=\"o\">&gt;</span><span class=\"p\">::</span><span class=\"n\">new_unchecked</span><span class=\"p\">(</span><span class=\"bp\">self</span><span class=\"p\">.</span><span class=\"n\">handle</span><span class=\"p\">)</span>\n<span class=\"w\">            </span><span class=\"p\">};</span>\n<span class=\"w\">            </span><span class=\"kd\">let</span><span class=\"p\">(</span><span class=\"n\">ret0</span><span class=\"p\">,)</span><span class=\"w\"> </span><span class=\"o\">=</span><span class=\"w\"> </span><span class=\"n\">callee</span><span class=\"p\">.</span><span class=\"n\">call_async</span><span class=\"p\">(</span><span class=\"n\">store</span><span class=\"p\">.</span><span class=\"n\">as_context_mut</span><span class=\"p\">(),(</span><span class=\"n\">arg0</span><span class=\"p\">,</span><span class=\"n\">arg1</span><span class=\"p\">,)).</span><span class=\"k\">await</span><span class=\"o\">?</span><span class=\"p\">;</span>\n<span class=\"w\">            </span><span class=\"n\">callee</span><span class=\"p\">.</span><span class=\"n\">post_return_async</span><span class=\"p\">(</span><span class=\"n\">store</span><span class=\"p\">.</span><span class=\"n\">as_context_mut</span><span class=\"p\">()).</span><span class=\"k\">await</span><span class=\"o\">?</span><span class=\"p\">;</span>\n<span class=\"w\">            </span><span class=\"nb\">Ok</span><span class=\"p\">(</span><span class=\"n\">ret0</span><span class=\"p\">)</span>\n</code></pre></div>\n<p>The docs say that if you call TypedFunc's <a href=\"https://docs.rs/wasmtime/latest/wasmtime/component/struct.TypedFunc.html#method.call_async\">call_async</a> method, you must call <a href=\"https://docs.rs/wasmtime/latest/wasmtime/component/struct.TypedFunc.html#method.post_return_async\">post_return_async</a>. If this snippet is cancelled _during_ that call to <code>call_async</code>. then it looks like <code>post_return_async</code> will never be called (and there doesn't seem to be a way to recover from that).</p>\n<p>Am I right that this code isn't cancel-safe? And if so, is there any way to recover from the cancellation?</p>\n</blockquote>",
        "id": 495416979,
        "sender_full_name": "Wasmtime GitHub notifications bot",
        "timestamp": 1737603121
    },
    {
        "content": "<p>alexcrichton <a href=\"https://github.com/bytecodealliance/wasmtime/issues/10088#issuecomment-2608811454\">commented</a> on <a href=\"https://github.com/bytecodealliance/wasmtime/issues/10088\">issue #10088</a>:</p>\n<blockquote>\n<p>Thanks for the report! Even setting aside components it's pretty unlikely that any core wasm module is cancel-safe in terms of dropping a <code>call_async</code> future. Destructors are not run with wasm on the stack meaning that any state in the wasm module is leaked including the stack pointer itself. Given that what the component model is doing here is codifying what you probably want anyway which is to throw away the component entirely whenever an async call is cancelled. Otherwise you have no way of knowing robustly what was on the wasm stack and what was cancelled on the wasm side.</p>\n<p>That's a bit of a winded way of saying that this is expected behavior. It's not intended to be recoverable once you drop a <code>call_async</code> future. The \"cancel safe\" part is that you're deterministically prevented from reentering the wasm module. Currently there's no way to opt-in to \"yes ok but I really know the wasm is cancel-safe\" and if that's what you're looking for here I think it'd be ok to add that to the API.</p>\n</blockquote>",
        "id": 495420109,
        "sender_full_name": "Wasmtime GitHub notifications bot",
        "timestamp": 1737605278
    },
    {
        "content": "<p>fitzgen closed <a href=\"https://github.com/bytecodealliance/wasmtime/issues/10088\">issue #10088</a>:</p>\n<blockquote>\n<p>Hello!</p>\n<p>I'm contributing to a project which calls async wasmtime exports. Sometimes, those exported functions start failing with the error \"wasm trap: cannot enter component instance\". I think the issue might be that the generated wasm client isn't cancel-safe.</p>\n<p>Here's the relevant snippet from the generated code (generated by wit-bindgen 0.38):</p>\n<div class=\"codehilite\" data-code-language=\"Rust\"><pre><span></span><code><span class=\"w\">            </span><span class=\"kd\">let</span><span class=\"w\"> </span><span class=\"n\">_enter</span><span class=\"w\"> </span><span class=\"o\">=</span><span class=\"w\"> </span><span class=\"n\">span</span><span class=\"p\">.</span><span class=\"n\">enter</span><span class=\"p\">();</span>\n<span class=\"w\">            </span><span class=\"kd\">let</span><span class=\"w\"> </span><span class=\"n\">callee</span><span class=\"w\"> </span><span class=\"o\">=</span><span class=\"w\"> </span><span class=\"k\">unsafe</span><span class=\"w\"> </span><span class=\"p\">{</span>\n<span class=\"w\">                </span><span class=\"n\">wasmtime</span><span class=\"p\">::</span><span class=\"n\">component</span><span class=\"p\">::</span><span class=\"n\">TypedFunc</span><span class=\"p\">::</span><span class=\"o\">&lt;</span><span class=\"p\">(</span><span class=\"kt\">u32</span><span class=\"p\">,</span><span class=\"w\"> </span><span class=\"o\">&amp;</span><span class=\"n\">Event</span><span class=\"p\">,),(</span><span class=\"nb\">Result</span><span class=\"o\">&lt;</span><span class=\"n\">Response</span><span class=\"p\">,</span><span class=\"n\">HandleError</span><span class=\"o\">&gt;</span><span class=\"p\">,)</span><span class=\"o\">&gt;</span><span class=\"p\">::</span><span class=\"n\">new_unchecked</span><span class=\"p\">(</span><span class=\"bp\">self</span><span class=\"p\">.</span><span class=\"n\">handle</span><span class=\"p\">)</span>\n<span class=\"w\">            </span><span class=\"p\">};</span>\n<span class=\"w\">            </span><span class=\"kd\">let</span><span class=\"p\">(</span><span class=\"n\">ret0</span><span class=\"p\">,)</span><span class=\"w\"> </span><span class=\"o\">=</span><span class=\"w\"> </span><span class=\"n\">callee</span><span class=\"p\">.</span><span class=\"n\">call_async</span><span class=\"p\">(</span><span class=\"n\">store</span><span class=\"p\">.</span><span class=\"n\">as_context_mut</span><span class=\"p\">(),(</span><span class=\"n\">arg0</span><span class=\"p\">,</span><span class=\"n\">arg1</span><span class=\"p\">,)).</span><span class=\"k\">await</span><span class=\"o\">?</span><span class=\"p\">;</span>\n<span class=\"w\">            </span><span class=\"n\">callee</span><span class=\"p\">.</span><span class=\"n\">post_return_async</span><span class=\"p\">(</span><span class=\"n\">store</span><span class=\"p\">.</span><span class=\"n\">as_context_mut</span><span class=\"p\">()).</span><span class=\"k\">await</span><span class=\"o\">?</span><span class=\"p\">;</span>\n<span class=\"w\">            </span><span class=\"nb\">Ok</span><span class=\"p\">(</span><span class=\"n\">ret0</span><span class=\"p\">)</span>\n</code></pre></div>\n<p>The docs say that if you call TypedFunc's <a href=\"https://docs.rs/wasmtime/latest/wasmtime/component/struct.TypedFunc.html#method.call_async\">call_async</a> method, you must call <a href=\"https://docs.rs/wasmtime/latest/wasmtime/component/struct.TypedFunc.html#method.post_return_async\">post_return_async</a>. If this snippet is cancelled _during_ that call to <code>call_async</code>. then it looks like <code>post_return_async</code> will never be called (and there doesn't seem to be a way to recover from that).</p>\n<p>Am I right that this code isn't cancel-safe? And if so, is there any way to recover from the cancellation?</p>\n</blockquote>",
        "id": 502346403,
        "sender_full_name": "Wasmtime GitHub notifications bot",
        "timestamp": 1740679382
    },
    {
        "content": "<p>fitzgen <a href=\"https://github.com/bytecodealliance/wasmtime/issues/10088#issuecomment-2688714092\">commented</a> on <a href=\"https://github.com/bytecodealliance/wasmtime/issues/10088\">issue #10088</a>:</p>\n<blockquote>\n<p>Closing this because it seems like the question was answered. If I'm mistaken feel free to reopen!</p>\n</blockquote>",
        "id": 502346407,
        "sender_full_name": "Wasmtime GitHub notifications bot",
        "timestamp": 1740679383
    },
    {
        "content": "<p>SupernaviX <a href=\"https://github.com/bytecodealliance/wasmtime/issues/10088#issuecomment-2688809505\">commented</a> on <a href=\"https://github.com/bytecodealliance/wasmtime/issues/10088\">issue #10088</a>:</p>\n<blockquote>\n<p>Oh yes thank you! I'm sorry, I forgot to follow up.<br>\nI rearchitected so that the wasmtime engine runs in a separate tokio task, and the rest of the app uses mpsc/oneshot channels to get request/response semantics. Now wasmtime calls are never cancelled, even if the task which called them gets cancelled itself.</p>\n<p>It absolutely makes sense that wasmtime can't recover from cancellation, it just surprised me because the generated code \"hides\" what's going on under the hood. I can't think of any way to make that behavior clearer (it's hard to document generated code), and once you know to expect it it's easy to work around.</p>\n</blockquote>",
        "id": 502353884,
        "sender_full_name": "Wasmtime GitHub notifications bot",
        "timestamp": 1740681838
    }
]